### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by manishPh**
Fix typo in self-hosting instructions

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @manishPh has signed the CLA. Thanks for the pull request!

**Comment by mickr** [comment]
Probably should make branches on your own fork and open PRs against the canonical / upstream repo.

**Comment by mickr** [comment]
@manishPh is this good to merge?

**Comment by manishPh** [comment]
@jstoffan @mickr will create new PR following the conventions. I actually found more typo(s).

**Pull request closed without merging**
