### PR TITLE
fix(preview): fix auto scroll issue with embed preview

### PR DESCRIPTION
**Pull request by Machoper**
## Issue
Scrolling jumps to bottom of page on embedded multi-page previews

## Summary of changes
- Add `{ block: 'nearest' }` as param to [`scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) to prevent the parent scrollbar from jumping around
- Fix a type to pass lint check

### Before
auto_scroll_before

### After
auto_scroll_after

### CODE REVIEW

**Review by JChan106 — COMMENTED** [review]
Did you test that scrolling works as usual non-embedded? Can you also test on different browser sizes?

**Comment by karelee7** [comment]
Can we also test it out on different browsers just to be safe?

**Comment by Machoper** [comment]
> Did you test that scrolling works as usual non-embedded? Can you also test on different browser sizes?

@JChan106 Yes, scrolling works well in the Webapp across all browser sizes.

> Can we also test it out on different browsers just to be safe?

@karelee7 Yes, I have tested on all supported browsers.

---

Adding two more gifs for reference

**Safari + embedded:**
auto_scroll_safari

**MS Edge + non-embedded:**
auto_scroll_edge

**Review by JChan106 — APPROVED** [review]
LGTM

**Review by karelee7 — APPROVED** [review]

**Pull request merged**
