### PR TITLE
feat: upgrade react-intl

### PR DESCRIPTION
**Pull request by soygitana**
❗ On hold: https://github.com/box/box-ui-elements/pull/3466 (stable version is needed) should go first, then Preview and Annotations

IMPORTANT:

- Minimal set of changes to solve the problem. 

Changes:

1. `react-intl` lib has been upgrade to v6.4.2

2. deprecated `addLocaleData` (react-intl/locale-data has been removed from react-intl) has been removed ([doc](https://formatjs.io/docs/react-intl/upgrade-guide-3x)).

 ---
Testing:

Make sure application and strings are not broken when language is changed. 

---
For more information, please check: 

- [official upgrade guide](https://formatjs.io/docs/react-intl/upgrade-guide-3x)
- upgrade process review guide in collaborative spreadsheet

### CODE REVIEW

**Comment by soygitana** [comment]
[2686de8](https://github.com/box/box-content-preview/pull/1509/commits/2686de892005e9de96092e92ef1568b50a76dab5):

I have to add resolution for `react-intl` to package.json file ( `"**/react-intl/**/@types/react": "^17.0.2"`). `react-intl` has set `@types/react` to version 16 || 17 || 18 (https://github.com/formatjs/formatjs/blob/main/package.json#L61) so yarn install the latest one, however `@types/react` 17 i 18 are incompatible. It caused a mismatch of types in some components.

**Comment by soygitana** [comment]
@bfoxx1906 Is there a specific reason why @box/frontend is set to "^6.4.0" when the latest version is 9? Should it remain on version 6 or can I upgrade it?

**Review by jstoffan — APPROVED** [review]
Code changes LGTM

**Comment by bfoxx1906** [comment]
> * official upgrade guide

No we just haven't updated it.

**Comment by soygitana** [comment]
Regarding `@box/frontend` package:

It seems that this repository only relies on the 'prettier' and 'eslint' modules from `@box/frontend`. It doesn't make use of i18n functions like language bundles, so there's no need to upgrade it in relation to the `react-intl` update. I'll keep `@box/frontend` at version 6, and you can update it later if necessary.

**Review by jstoffan — APPROVED** [review]
🚀

**Comment by soygitana** [comment]
❗ On hold: [BUIE](https://github.com/box/box-ui-elements/pull/3466) should go first, then Preview and Annotations (confirmed by @greg-in-a-box)

**Pull request closed without merging**
