### PR TITLE
Chore: Change webpack source maps to 'inline-cheap-source-map'

### PR DESCRIPTION
**Pull request by jeremypress**
Options can be found here: https://webpack.js.org/configuration/devtool/

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @jeremypress has signed the CLA. Thanks for the pull request!

**Comment by jeremypress** [comment]
Doesn't affect our initial build time too much, but it reduces the rebuild time (when using watch) by almost 50%.

**Comment by priyajeet** [comment]
Does it work? We used inline-source-map, because it was more accurate and less brittle.

**Comment by jeremypress** [comment]
@priyajeet I'll do a full browser check

**Comment by jeremypress** [comment]
Looks like IE and Edge need something inline, so switching to 'inline-cheap-source-map'

**Pull request merged**
